substitutions:
  name: "bedroom-ac"
  friendly_name: "Bedroom AC"
  board: "esp32-s3-devkitc-1"
  rx_pin: "GPIO18"
  tx_pin: "GPIO17"
  api_encryption_key: !secret bedroom_ac_api_key
  ota_password: !secret bedroom_ac_ota_password

packages:
  fujitsu_ac: !include ../common/fujitsu-ac-common.yaml
